# SonarQube Project Analysis Exclusions
# Ignore legacy/abandoned code from the Sonar Quality Gate to prevent false security hotspots
sonar.exclusions=Finja-music/Not Maintained/**,TESTING.md,README.md
