# ======================================================================
#          Finja Web Crawler - Docker Compose
# ======================================================================
#
#   Project: Finja - Twitch Interactivity Suite
#   Module: finja-web-crawler
#   Author: J. Apps (JohnV2002 / Sodakiller1)
#   Version: 1.0.0
#
# ----------------------------------------------------------------------
#
#   Copyright (c) 2026 J. Apps
#   Licensed under the Apache License 2.0
#
# ======================================================================

version: '3.8'
services:
  tor:
    image: dperson/torproxy
    container_name: tor
    ports:
      - "9050:9050"
    restart: unless-stopped

  search-proxy:
    build: .
    container_name: duckduckgo_proxy
    ports:
      - "8080:80"
    depends_on:
      - tor
    restart: unless-stopped
    env_file:
      - .env
