"""
======================================================================
         Finja Omni Test – Benchmark Comparison
======================================================================

  Project: Finja - Twitch Interactivity Suite
  Module:  finja-omni-test / vergleich
  Author:  J. Apps (JohnV2002 / Sodakiller1)
  Version: 1.0.0

----------------------------------------------------------------------

  Copyright (c) 2026 J. Apps
  Licensed under the MIT License

  Made with ❤️ by Sodakiller1 (J. Apps / JohnV2002)
  Website: https://jappshome.de
  Support: https://buymeacoffee.com/J.Apps

----------------------------------------------------------------------
 Description:
----------------------------------------------------------------------
  Compares OCR benchmark summaries (generated by rapid_ocr_de.py).
  If ground_truth.json is available, also calculates accuracy (Precision/Recall).
======================================================================
"""

import os
import glob
import json

RESULTS_DIR  = "benchmark_results"
GROUND_TRUTH = "ground_truth.json"
OUT_FILE     = "vergleich.txt"

# Load truth (if available)
truth = {}
if os.path.exists(GROUND_TRUTH):
    with open(GROUND_TRUTH, encoding="utf-8") as f:
        truth = json.load(f)
    print(f"Ground Truth loaded: {len(truth)} frames "
          f"(Text: {sum(v == 'text' for v in truth.values())}, "
          f"Empty: {sum(v == 'leer' for v in truth.values())})\n")
else:
    print("[i] No ground_truth.json -> accuracy will be skipped.\n")

# Collect all summary.json
summaries = []
for jf in glob.glob(os.path.join(RESULTS_DIR, "*", "summary.json")):
    try:
        with open(jf, encoding="utf-8") as f:
            summaries.append(json.load(f))
    except Exception as e:
        print(f"[!] Could not read '{jf}': {e}")

if not summaries:
    print(f"No 'summary.json' found in '{RESULTS_DIR}/*/'. Run benchmark first!")
    raise SystemExit(1)


def accuracy(summary):
    """Compares model predictions against the truth.

    Returns: Total accuracy, text recall (text found if there),
    empty recall (empty recognized if none there).
    """
    preds = summary.get("predictions", {})
    if not truth or not preds:
        return None

    correct = total = 0
    text_hit = text_tot = 0
    leer_hit = leer_tot = 0

    for name, real in truth.items():
        pred = preds.get(name)
        if pred is None:
            continue
        total += 1
        # error counts as incorrect
        if pred == real:
            correct += 1
        if real == "text":
            text_tot += 1
            if pred == "text":
                text_hit += 1
        elif real == "leer":
            leer_tot += 1
            if pred == "leer":
                leer_hit += 1

    if total == 0:
        return None
    return {
        "acc":       100 * correct / total,
        "text_rec":  100 * text_hit / text_tot if text_tot else 0,
        "leer_rec":  100 * leer_hit / leer_tot if leer_tot else 0,
    }


# Append accuracy
for s in summaries:
    s["_acc"] = accuracy(s)

# Sorting: if accuracy present -> best accuracy first, otherwise fastest
have_acc = any(s["_acc"] for s in summaries)
if have_acc:
    summaries.sort(key=lambda s: -(s["_acc"]["acc"] if s["_acc"] else -1))
else:
    summaries.sort(key=lambda s: s.get("avg_s", 9e9))

# --- Build table ---
if have_acc:
    headers = ["Model", "Acc%", "Text%", "Empty%", "Err", "Avg s", "Median", "FPS", "Total s"]
    def build_row(s):
        a = s["_acc"]
        return [
            s.get("model", "-"),
            f"{a['acc']:.1f}"      if a else "-",
            f"{a['text_rec']:.1f}" if a else "-",
            f"{a['leer_rec']:.1f}" if a else "-",
            str(s.get("errors", "-")),
            str(s.get("avg_s", "-")),
            str(s.get("median_s", "-")),
            str(s.get("fps", "-")),
            str(s.get("total_time_s", "-")),
        ]
else:
    headers = ["Model", "Text", "Empty", "Err", "Avg s", "Median", "Fastest", "Slowest", "FPS", "Total s"]
    def build_row(s):
        return [str(s.get(k, "-")) for k in
                ["model", "with_text", "empty", "errors", "avg_s",
                 "median_s", "fastest_s", "slowest_s", "fps", "total_time_s"]]

rows = [build_row(s) for s in summaries]

widths = [len(h) for h in headers]
for row in rows:
    for i, cell in enumerate(row):
        widths[i] = max(widths[i], len(cell))


def fmt(cells):
    return "  ".join(
        c.ljust(widths[i]) if i == 0 else c.rjust(widths[i])
        for i, c in enumerate(cells)
    )


sep = "-" * (sum(widths) + 2 * (len(widths) - 1))

title = "MODEL COMPARISON  (best accuracy first)" if have_acc \
        else "MODEL COMPARISON  (fastest first)"

lines = ["=" * len(sep), "  " + title, "=" * len(sep),
         fmt(headers), sep]
lines += [fmt(r) for r in rows]
lines.append(sep)

# Conclusion
best = summaries[0]
if have_acc and best["_acc"]:
    lines.append(f"\n  -> Best Accuracy: {best['model']}  "
                 f"({best['_acc']['acc']:.1f}% correct, {best['avg_s']} s/Frame)")
    # Best compromise: Accuracy per second (rough heuristic)
    def score(s):
        return (s['_acc']['acc'] if s['_acc'] else 0) / max(s.get('avg_s', 1), 0.001)
    sweet = max(summaries, key=score)
    lines.append(f"  -> Best Speed/Accuracy-Mix: {sweet['model']}  "
                 f"({sweet['_acc']['acc']:.1f}% @ {sweet['avg_s']} s/Frame)")
else:
    lines.append(f"\n  -> Fastest Model: {best['model']}  "
                 f"({best.get('avg_s')} s/Frame, ~{best.get('fps')} FPS)")

if have_acc:
    lines.append("\n  Legend:  Acc% = all frames correct | "
                 "Text% = text found if there | "
                 "Empty% = empty recognized if none there")

table = "\n".join(lines)
print(table)

with open(OUT_FILE, "w", encoding="utf-8") as f:
    f.write(table + "\n")

print(f"\nSaved: {OUT_FILE}")
