"""
YourAI AI - Discord DM Tool
============================
Sends DMs to whitelisted Discord users.

Usage:
    from tools.discord_dm import send_discord_dm
"""

import os
import sys
from typing import Dict, Any

# The tools package needs access to parent modules
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import _paths  # noqa: F401

from display import log, log_exception, Fore
from exceptions import YourAIToolExecutionError, YourAIUnexpectedError, YourAIImportError

from helpers.platform_links import _load as _pl_load_links


def _get_dm_whitelist() -> dict:
    """Build a discord_id -> user_key map from platform_links (dm_allowed=true only)."""
    data = _pl_load_links()
    return {
        did: ukey
        for ukey, info in data.items()
        if info.get("dm_allowed")
        for did in info.get("discord_ids", [])
    }


DISCORD_DM_WHITELIST = _get_dm_whitelist()


def send_discord_dm(context: Dict[str, Any], debug: Any = None) -> Dict[str, Any]:
    """
    Send a DM to a whitelisted Discord user.

    The tool router detects the trigger and calls this tool. YourAI generates
    the message, and this tool sends it.

    Args:
        context (Dict[str, Any]): Dict with:
            - "question": Original user input (e.g. "DM Mom that I love her").
            - "user_name": Who issued the command.
            - "dm_target": Target user key from the whitelist (e.g. "Mom", "Bendy").
            - "dm_message": The message to send (generated by YourAI).
        debug (Any): Optional dashboard debug client.

    Returns:
        Dict[str, Any]: {"success": bool, "result": str, "error": str|None}.
    """
    if debug is None:
        class DummyDebug:
            def __getattr__(self, name):
                return lambda *args, **kwargs: None
        debug = DummyDebug()

    debug.node_start("discord_dm", input_data="Sending Discord DM")

    # Extract target from context or from the question
    target_key = context.get("dm_target")
    dm_message = context.get("dm_message")

    if not target_key:
        # Try to detect the target from the question
        question = context.get("question", "").lower()
        for discord_id, user_key in DISCORD_DM_WHITELIST.items():
            if user_key.lower() in question:
                target_key = user_key
                break

    if not target_key:
        log("DISCORD", "⚠️ DM tool: no target detected", Fore.YELLOW)
        debug.node_end("discord_dm")
        return {
            "success": False,
            "result": None,
            "error": "No DM target detected. Tell me WHO I should message!",
            "needs_generation": False
        }

    # Find the Discord ID for the target
    target_discord_id = None
    for discord_id, user_key in DISCORD_DM_WHITELIST.items():
        if user_key.lower() == target_key.lower():
            target_discord_id = int(discord_id)
            break

    if not target_discord_id:
        log("DISCORD", f"🚫 DM tool: '{target_key}' not in whitelist!", Fore.RED)
        debug.node_end("discord_dm")
        return {
            "success": False,
            "result": None,
            "error": f"'{target_key}' is not in my DM whitelist! I can only message certain people.",
            "needs_generation": False
        }

    if not dm_message:
        # YourAI must generate the message first
        log("DISCORD", f"📝 DM tool: need a message for {target_key}", Fore.YELLOW)
        debug.node_end("discord_dm")
        return {
            "success": False,
            "result": None,
            "error": None,
            "needs_generation": True,
            "dm_target": target_key,
            "generation_prompt": f"Write a Discord DM message to {target_key}. Context: {context.get('question', '')}"
        }

    # Get the Discord bot and send the DM
    try:
        import discord_client
        bot = discord_client.bot

        if not bot.connected:
            log("DISCORD", "⚠️ DM tool: bot not connected!", Fore.YELLOW)
            debug.node_end("discord_dm")
            return {
                "success": False,
                "result": None,
                "error": "Discord bot is not connected! Cannot send a DM."
            }

        bot.send_dm(target_discord_id, dm_message)

        log("DISCORD", f"📩 DM sent to {target_key}: {dm_message[:50]}...", Fore.GREEN)
        debug.info("discord_dm", f"DM sent to {target_key}: {dm_message[:50]}...")
        debug.node_end("discord_dm")

        return {
            "success": True,
            "result": f"DM sent to {target_key}! Message: \"{dm_message[:100]}\"",
            "error": None,
            "dm_target": target_key,
            "dm_message": dm_message
        }

    except ImportError as e:
        err = YourAIImportError("discord_client", module="discord_dm", cause=e)
        log_exception("DISCORD", err)
        debug.node_end("discord_dm")
        return {
            "success": False,
            "result": None,
            "error": "Discord client not loaded (is USE_DISCORD off?)"
        }

    except Exception as e:
        err = YourAIToolExecutionError("Failed to send the DM", tool_name="discord_dm", cause=e)
        log_exception("DISCORD", err)
        debug.error("discord_dm", err.short(), exception=e)
        debug.node_end("discord_dm")
        return {
            "success": False,
            "result": None,
            "error": f"Failed to send: {e}"
        }
