# =====================================================================
#  Project: Finja Cloud Memory - Docker Compose
#  Version: 1.1.1
#  Author:  JohnV2002 (J. Apps / Sodakiller1)
#  License: MIT
#
# =====================================================================
#  Updates v1.1.1:
#  + Added backups Folder
#
#  Updates v1.1.0:
#  + Added volume mounts for 'user_audio' and 'tts_cache'.
#  + Added 'user' directive to fix permission issues on Linux hosts.
# =====================================================================

version: '3.8'

services:
  # Definiert den Haupt-Service für den Memory-Server
  finja-memory-server:
    # Baut das Docker-Image aus dem Dockerfile im aktuellen Verzeichnis
    build: .
    # Gibt dem Container einen festen, wiedererkennbaren Namen
    container_name: finja-memory-server
    # Liest die Konfiguration (API-Key) aus der .env-Datei
    # Dies ist sicherer, als die Datei ins Image zu kopieren
    env_file:
      - .env
    # Mappt den Ordner für die Speicherdaten auf den Host, damit die Daten
    # auch nach einem Löschen des Containers erhalten bleiben
    volumes:
        - ./user_audio:/app/user_audio
        - ./tts_cache:/app/tts_cache
        - ./user_memories:/app/user_memories
        - ./backups:/app/backups
    # Leitet den Port 8000 des Hosts auf den Port 8000 im Container um
    ports:
      - "8000:8000"

    user: "${UID:-1000}:${GID:-1000}"
    # Startet den Container automatisch neu, es sei denn, er wird manuell gestoppt
    restart: unless-stopped