"""
YourAI AI - Dashboard Images
===========================
Helper utility for persisting base64-encoded visual artwork generated by the image model.

Main Responsibilities:
- Parse and decode inline base64 data URIs.
- Save image files to the frontend asset directory.
- Return relative dashboard URLs for frontend presentation.

Side Effects:
- Creates frontend asset directories and writes files to disk.
"""

import base64
import os
import time

import _paths  # noqa: F401

from display import Fore, log, log_exception
from exceptions import YourAIUnexpectedError


def prepare_dashboard_image_url(image_url: str) -> str:
    """
    Persists inline base64 data URI images to disk and returns a relative web-accessible URL.

    Args:
        image_url (str): The raw input image URL (or data URI scheme).

    Returns:
        str: The saved local asset web path, or the original image URL on failure/bypass.
    """
    if not isinstance(image_url, str) or not image_url.startswith("data:"):
        return image_url

    try:
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        gen_dir = os.path.join(project_root, "frontend", "generated")
        os.makedirs(gen_dir, exist_ok=True)
        _, encoded = image_url.split(",", 1)
        img_bytes = base64.b64decode(encoded)
        filename = f"yourai_art_{int(time.time())}.png"
        with open(os.path.join(gen_dir, filename), "wb") as f:
            f.write(img_bytes)
        stored_url = f"/generated/{filename}"
        log("DASHBOARD", f"Image saved -> {stored_url}", Fore.CYAN)
        return stored_url
    except Exception as e:
        err = YourAIUnexpectedError(cause=e, module="dashboard_image_ready_save")
        log_exception("DASHBOARD", err)
        log("DASHBOARD", f"Failed to save image: {e}", Fore.YELLOW)
        return image_url

