name: Docker Security & Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  scan-and-build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: Memory
            path: finja-Open-Web-UI/finja-Memory
            tag: finja-memory
          - name: OCR
            path: finja-Open-Web-UI/finja-ocr
            tag: finja-ocr
          - name: Web-Crawler
            path: finja-Open-Web-UI/finja-web-crawler
            tag: finja-web-crawler

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Snyk and Authenticate
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          npm install -g snyk
          snyk auth $SNYK_TOKEN

      - name: Scan Dockerfile for IAC issues
        working-directory: ./${{ matrix.service.path }}
        run: snyk iac test Dockerfile --severity-threshold=high

      - name: Scan Python source code (SAST)
        working-directory: ./${{ matrix.service.path }}
        run: snyk code test --severity-threshold=high

      - name: Build image for ${{ matrix.service.name }}
        working-directory: ./${{ matrix.service.path }}
        run: |
          docker build . --file Dockerfile --tag ${{ matrix.service.tag }}:latest
          echo "✅ Built image: ${{ matrix.service.tag }}:latest"

      - name: Run Snyk Container Scan
        working-directory: ./${{ matrix.service.path }}
        run: snyk container test ${{ matrix.service.tag }}:latest --severity-threshold=high

      - name: Print success message
        run: echo "✅ ${{ matrix.service.tag }}:latest scanned and built successfully"
