# Name des Workflows
name: Docker Build Check

# Löst den Workflow bei Push oder Pull-Request aus
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Definiert die einzelnen Jobs für jeden Service
jobs:
  # --- JOB 1: Memory ---
  build-memory:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Docker image for Memory
        working-directory: ./finja-Open-Web-UI/finja-Memory
        run: docker build . --file Dockerfile --tag finja-memory:latest

  # --- JOB 2: OCR ---
  build-ocr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Docker image for OCR
        working-directory: ./finja-Open-Web-UI/finja-ocr
        run: docker build . --file Dockerfile --tag finja-ocr:latest

  # --- JOB 3: Web-Crawler ---
  build-web-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build Docker image for Web-Crawler
        working-directory: ./finja-Open-Web-UI/finja-web-crawler
        run: docker build . --file Dockerfile --tag finja-web-crawler:latest
