# .github/workflows/memory-build.yml
name: Memory Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Build Docker image for Memory
        working-directory: ./finja-Open-Web-UI/finja-Memory
        run: docker build . --file Dockerfile --tag finja-memory:latest
