# .github/workflows/ocr-build.yml
name: OCR Build Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        
      - name: Build Docker image for OCR
        working-directory: ./finja-Open-Web-UI/finja-ocr
        run: docker build . --file Dockerfile --tag finja-ocr:latest
