/**
 * Glorpo Native Dictionary
 * ========================
 * Provides the generated Glorpo-to-Python token map for the native runner.
 *
 * Main Responsibilities:
 * - Expose DEGLORPO_MAP to C++ sources.
 * - Keep tokens sorted longest-first to prevent partial matches.
 *
 * Side Effects:
 * - Generated from glorpo.py by gen_dict.py.
 */
#pragma once
#include <vector>
#include <string>
#include <utility>

// Auto-generated from glorpo.py GLORPO_DICT (133 tokens).
// Do not edit manually. Regenerate with:
//   python3 gen_dict.py
//
// Glorpo token -> Python token, sorted longest-first (prevents partial matches).
const std::vector<std::pair<std::string, std::string>> DEGLORPO_MAP = {
    {"__glorpmirror__",               "__repr__"},
    {"__glorpwithin__",               "__contains__"},
    {"__glorpbirth__",                "__init__"},
    {"__glorpleave__",                "__exit__"},
    {"__glorpslots__",                "__slots__"},
    {"__glorpface__",                 "__str__"},
    {"__glorpsize__",                 "__len__"},
    {"__glorpwalk__",                 "__iter__"},
    {"__glorpstep__",                 "__next__"},
    {"__glorpcome__",                 "__enter__"},
    {"__glorpgrab__",                 "__getitem__"},
    {"__glorpname__",                 "__name__"},
    {"__glorpmain__",                 "__main__"},
    {"__glorplist__",                 "__all__"},
    {"__glorpkind__",                 "__class__"},
    {"__glorpdata__",                 "__dict__"},
    {"glorpcomplex",                  "complex"},
    {"glorpwhisper",                  "lower"},
    {"__glorpput__",                  "__setitem__"},
    {"__glorpzap__",                  "__delitem__"},
    {"__glorpdoc__",                  "__doc__"},
    {"glorpnotyet",                   "NotImplemented"},
    {"glorpalways",                   "finally"},
    {"glorpfrozen",                   "frozenset"},
    {"glorpstatic",                   "staticmethod"},
    {"glorpclassy",                   "classmethod"},
    {"glorpdivmod",                   "divmod"},
    {"glorpscream",                   "upper"},
    {"__glorpdo__",                   "__call__"},
    {"glorpcheck",                    "match"},
    {"glorpcatch",                    "except"},
    {"glorpswear",                    "assert"},
    {"glorpreach",                    "nonlocal"},
    {"glorpfloat",                    "float"},
    {"glorptuple",                    "tuple"},
    {"glorpbytes",                    "bytes"},
    {"glorpslice",                    "slice"},
    {"glorpthing",                    "object"},
    {"glorpkidof",                    "issubclass"},
    {"glorpsuper",                    "super"},
    {"glorprange",                    "range"},
    {"glorpcount",                    "enumerate"},
    {"glorpmorph",                    "map"},
    {"glorpchonk",                    "max"},
    {"glorpround",                    "round"},
    {"glorpbegin",                    "startswith"},
    {"glorptally",                    "count"},
    {"glorpwhere",                    "index"},
    {"glorpshove",                    "append"},
    {"glorpyoink",                    "pop"},
    {"glorpstuff",                    "items"},
    {"glorbelif",                     "elif"},
    {"glorpelse",                     "else"},
    {"glorploop",                     "while"},
    {"glorpsnap",                     "break"},
    {"glorpskip",                     "continue"},
    {"glorpnull",                     "pass"},
    {"glorpwhen",                     "case"},
    {"glorpback",                     "return"},
    {"glorpgive",                     "yield"},
    {"glorpfast",                     "async"},
    {"glorpwait",                     "await"},
    {"glorpvoid",                     "None"},
    {"glorpfrom",                     "from"},
    {"glorpyeet",                     "raise"},
    {"glorpwide",                     "global"},
    {"glorpwith",                     "with"},
    {"glorpshow",                     "repr"},
    {"glorpopen",                     "open"},
    {"glorptext",                     "str"},
    {"glorpbool",                     "bool"},
    {"glorplist",                     "list"},
    {"glorptype",                     "type"},
    {"glorpsize",                     "len"},
    {"glorphash",                     "hash"},
    {"glorplook",                     "dir"},
    {"glorpvars",                     "vars"},
    {"glorpcall",                     "callable"},
    {"glorpgrab",                     "getattr"},
    {"glorpdrop",                     "delattr"},
    {"glorpprop",                     "property"},
    {"glorpsift",                     "filter"},
    {"glorpsort",                     "sorted"},
    {"glorpflip",                     "reversed"},
    {"glorpwalk",                     "iter"},
    {"glorpnext",                     "next"},
    {"glorpsmol",                     "min"},
    {"glorpchop",                     "split"},
    {"glorptrim",                     "strip"},
    {"glorpswap",                     "replace"},
    {"glorpseek",                     "find"},
    {"glorpglue",                     "join"},
    {"glorpkeys",                     "keys"},
    {"glorpvals",                     "values"},
    {"glorpself",                     "self"},
    {"glorpach",                      "for"},
    {"glorpkin",                      "class"},
    {"glorpyes",                      "True"},
    {"glorpand",                      "and"},
    {"glorpnot",                      "not"},
    {"glorpget",                      "import"},
    {"glorptry",                      "try"},
    {"glorpbye",                      "del"},
    {"glorpask",                      "input"},
    {"glorpfmt",                      "format"},
    {"glorpnum",                      "int"},
    {"glorpmap",                      "dict"},
    {"glorpbag",                      "set"},
    {"glorpisa",                      "isinstance"},
    {"glorphas",                      "hasattr"},
    {"glorpset",                      "setattr"},
    {"glorpzip",                      "zip"},
    {"glorpabs",                      "abs"},
    {"glorpsum",                      "sum"},
    {"glorppow",                      "pow"},
    {"glorphex",                      "hex"},
    {"glorpoct",                      "oct"},
    {"glorpchr",                      "chr"},
    {"glorpord",                      "ord"},
    {"glorpbin",                      "bin"},
    {"glorpany",                      "any"},
    {"glorpall",                      "all"},
    {"glorpend",                      "endswith"},
    {"glorbda",                       "lambda"},
    {"glorpno",                       "False"},
    {"glorpor",                       "or"},
    {"glorpis",                       "is"},
    {"glorpin",                       "in"},
    {"glorpas",                       "as"},
    {"glorpid",                       "id"},
    {"glorb",                         "if"},
    {"glorp",                         "print"},
    {"gloo",                          "def"}
};
